version: '3.8'

services:

  mariadb:
    build: ./requirements/mariadb # Build from local Dockerfile
    container_name: mariadb
    image: mariadb_custom
    restart: always # Automatic restart
    env_file:
      - .env # Environment variables
    volumes:
      - mariadb_data:/var/lib/mysql # Data persistence
    networks:
      - inception # Private network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress_custom
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy # Wait until MariaDB is healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx_custom
    restart: always
    ports:
      - "443:443" # Only port exposed to the outside world
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

volumes:

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge